const routes = {
    dashboard: "Dashboard",
    onboarding: 'OnboardingScreen',
    taxInvoice: 'TaxInvoice',
    login: 'login',
    Signup: 'Signup',
    Verification: 'Verification',
    MobileInput: 'MobileInput',
    MobileVerification: 'MobileVerification',
    RechargeWallet: 'RechargeWallet',
    Profile: 'Profile',
    OngoingDetails: 'OngoingDetails',
    EvModal: 'EvModal',
    AddEvModal: 'AddEvModal',
    SelectVehicle: 'SelectVehicle',
    Preference: 'Preference',
    SearchLocation: 'SearchLocation',
    Favoruite: 'Favoruite',
    ChargingStation: 'ChargingStation',
    ChargingStationList: 'ChargingStationList',
    Support: 'Support',
    ChangePassword: 'ChangePassword',
    ReferAndEarn: 'ReferAndEarn',
    PaymentMethod: 'PaymentMethod',
    Order: 'Order',
    ChargingKey: 'ChargingKey',
    Store: 'Store',
    OrderDetails: 'OrderDetails',
    FortumChargeAndDriveCard: 'FortumChargeAndDriveCard',
    ActivateCard: 'ActivateCard',
    CompleteKYC: 'CompleteKYC',
    Passbook: 'Passbook',
    PaymentScreenJuspay: 'PaymentScreenJuspay',
    MyCart:'MyCart',
    StoreDetails:'StoreDetails',
}

export default routes