const routes = {
    dashboard:"Dashboard",
    onboarding:'OnboardingScreen',
    taxInvoice:'TaxInvoice',
    login:'login',
    Signup:'Signup',
    Verification:'Verification',
    RechargeWallet:'RechargeWallet',
    Profile:'Profile',
    OngoingDetails:'OngoingDetails',
    EvModal:'EvModal',
    AddEvModal:'AddEvModal',
    SelectVehicle:'SelectVehicle',
    Preference:'Preference',
    SearchLocation:'SearchLocation',
    Favoruite:'Favoruite',
    ChargingStation:'ChargingStation',
    ChargingStationList:'ChargingStationList',
    Support:'Support',
    ChangePassword:'ChangePassword',
    ReferAndEarn:'ReferAndEarn',
    PaymentMethod:'PaymentMethod',
    Order:'Order',
    ChargingKey:'ChargingKey',
    Store:'Store',
    OrderDetails:'OrderDetails',
}

export default routes